trigger:
- main

pool:
  name: Default

steps:
- task: DockerInstaller@0

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'basitkhan50076/hello_world'
    command: 'buildAndPush'
    Dockerfile: 'node-js-dummy-test/Dockerfile'
    tags: 'latest'
